[calendar]
url = "https://www.feiertage-deutschland.de/kalender-download/ics/feiertage-deutschland.ics"
replace_links = [
    { keyword = "Entropia, Hauptraum", link = "[[Räume#Hauptraum|Hauptraum]]" },
    { keyword = "Entropia, Nebenraum", link = "[[Räume#Nebenraum|Nebenraum]]" },
]

[wiki]
api_url = "https://xxx/api.php"
page_title = "Vorlage:Feiertage"
username = "Icsbot"
password = ""
edit_summary = "Kalender automatisch aktualisiert (ics-to-wiki)"
info = "HIER NICHTS BEARBEITEN! Diese Tabelle wird automatisch durch ein Bot aus Kalenderdaten aktualisiert. Bitte die Daten im Kalender pflegen."
